name: imagepicker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  image_picker: ^1.2.0
  image_picker_windows: ^0.2.2
  camera: ^0.11.2
  camera_windows: ^0.2.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
